"""Write private/REPORT_SYM003.md from the SYM-003 result files. No figure typed by hand."""
from __future__ import annotations

import json
import os

from features import HERE

PRIV = os.path.join(HERE, "private")
R = json.load(open(os.path.join(PRIV, "results", "sym003_metrics.json")))
AU = json.load(open(os.path.join(PRIV, "results", "sym003_audit.json")))
EX = json.load(open(os.path.join(PRIV, "results", "sym003_descriptive_extras.json")))
FZ = json.load(open(os.path.join(PRIV, "models", "SYM003_FROZEN.json")))
FO = json.load(open(os.path.join(PRIV, "models", "sym003_final_baseline_plus_O.json")))
MODELS = ["baseline", "baseline+W", "baseline+S", "baseline+O", "baseline+all", "market_archived"]
LAB = {"baseline": "Baseline (SYM-002 regularised LR, 23 gaps)", "baseline+W": "+ W wrestling matchup",
       "baseline+S": "+ S striking matchup", "baseline+O": "+ O opponent-adjusted", "baseline+all": "+ all three",
       "market_archived": "Archived market (timestamps unverified)"}
DESC = {"W1": "expected takedowns (my TD rate × their TDs conceded)", "W2": "expected control (my control × their control conceded)",
        "W3": "takedown success (my TD accuracy × their TD-defence failure)", "S1": "expected strikes landed (my output × their absorption)",
        "S2": "expected accuracy (my accuracy × their defensive failure)", "S3": "expected knockdowns (my KD rate × their KDs conceded)",
        "O1": "strikes landed vs what each opponent usually allowed", "O2": "strikes absorbed vs what each opponent usually landed (positive = absorbed less)",
        "O3": "takedowns landed vs what each opponent usually conceded", "O4": "takedowns conceded vs what each opponent usually landed (positive = conceded fewer)",
        "O5": "control won vs what each opponent usually conceded", "O6": "control conceded vs what each opponent usually won (positive = conceded less)"}


def f(x, d=4):
    return f"{x:.{d}f}"


def table(rows, cols):
    return "\n".join(["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)] + ["| " + " | ".join(map(str, r)) + " |" for r in rows])


def main():
    P, H, V, V26 = R["pooled_2021_2025"], R["historical_2026"], R["vs_baseline_2021_2025"], R["vs_baseline_2026"]
    o = V["baseline+O"]
    md = []
    w = md.append
    w("# SYM-003: do better matchup features add information? (report)\n")
    w("_Private, **exploratory** research. Every fight scored here had already been examined. Rules frozen in "
      "`config_sym003.json` (commit `9bf99be2`) before any feature was built. Generated by `make_report_sym003.py`._\n")
    w("## Verdict\n")
    w(f"- **Did new information help?** A little, and only one kind of it. Adding **opponent-adjusted performance (O)** "
      f"lowered log loss by {f(-o['diff'])} on {o['n_fights']} fights / {o['n_events']} events (2021–2025, 95% interval "
      f"{f(o['ci95'][0])} to {f(o['ci95'][1])}), better in {o['folds_better_of_5']} of 5 years. That **meets the "
      "pre-registered rule.** It was also better on the already-studied 2026 fights "
      f"({f(V26['baseline+O']['diff'])}, {V26['baseline+O']['n_fights']} fights).")
    w(f"- **Proportion.** The gain is small. It closes about {EX['share_of_baseline_to_market_gap_closed_by_O']*100:.0f}% of the "
      f"gap between the baseline and the archived market, and it does not raise accuracy "
      f"({P['baseline+O']['accuracy']*100:.1f}% vs {P['baseline']['accuracy']*100:.1f}%). Four groups were tested; with a "
      f"Bonferroni correction for that, O's interval becomes {f(EX['baseline+O']['bonferroni_4_tests_98.75pct_ci'][0])} to "
      f"{f(EX['baseline+O']['bonferroni_4_tests_98.75pct_ci'][1])} and **just crosses zero** (descriptive, not pre-registered).")
    w(f"- **Which groups helped or hurt?** **O helped.** **W (wrestling matchup) did nothing or slightly hurt** "
      f"({V['baseline+W']['diff']:+.4f}, {V['baseline+W']['folds_better_of_5']}/5 years). **S (striking matchup) was a wash** "
      f"({V['baseline+S']['diff']:+.4f}, {V['baseline+S']['folds_better_of_5']}/5). **All three together** "
      f"({V['baseline+all']['diff']:+.4f}, interval {f(V['baseline+all']['ci95'][0])} to {f(V['baseline+all']['ci95'][1])}) "
      "was carried by O and diluted by the others, and did not meet the rule. W and S were mostly already in the "
      "baseline, as the pre-fit diagnostic said they would be (§2).")
    w("- **Enough to justify more formula research?** The pre-registered gate is technically open, because O passed. On "
      "proportion, a new symbolic search is **not yet justified**. The gain is one group, it is modest, it is not robust "
      "to a multiple-test correction, and SYM-002 showed that symbolic search on these inputs fits noise. The better next "
      "step is to freeze and wait for unseen fights. If O holds up there, a *narrow* search over the O inputs only, "
      "pre-registered, would be the proportionate follow-up.")
    w("- **What to freeze.** As pre-designated: **baseline + O vs baseline**, hashes below, scored only on events after "
      "2026-10-07.")
    w(f"- **Against the market:** every model here is still clearly worse than the archived market "
      f"({f(P['market_archived']['logloss'])} vs {f(P['baseline+O']['logloss'])} for the best). The market's timestamps "
      "are placeholders, so neither direction says anything about a bettable price. No ROI or CLV.\n")
    w("In plain English: **it helps a little to judge a fighter's striking by who they did it against.** Landing more than "
      "an opponent usually allows, and getting hit less than that opponent usually lands, says slightly more than raw "
      "strike counts do. Knowing how the two styles collide, beyond the gaps already in the model, did not help.\n")

    w("## 1. Correction carried over from SYM-002\n")
    w("SYM-002's report previously called the 61.5% match 'suggestive' of leakage in v1. That was wrong, and it has been "
      "corrected in place. A rounded accuracy matched on a different cohort is not evidence about how v1 was built. v1 "
      "reportedly rebuilt its statistics from prior fights, and its implementation was not inspected, so **v1's leakage "
      "status is unverified.**\n")

    w("## 2. What the existing features already covered, and what was missing\n")
    w(table([["Opponent strength", "`elo`, `opp_elo_mean`", "strength-adjusted *stats*: Elo adjusts wins for the opposition, but every striking/wrestling rate was raw"],
             ["Recent performance", "`last3_win_rate`, `fights_24m`, layoff; Elo is sequential", "recency in *stats*: all rates were equal-weight career averages"],
             ["Style interactions", "none, only separate additive gaps", "cross terms on the natural scale (a log-scale product splits into gaps the model already has)"],
             ["Conceded rates", "`td_def` ratio only", "takedowns and knockdowns conceded per 15 min"]],
            ["question", "already covered by", "actually missing"]))
    w("\n**Pre-fit diagnostic (outcome-free, computed before any scoring):** R² of each new feature against the 23 baseline "
      f"gaps, {AU['representation']['n_rows']} training fights 2008–2020.\n")
    r2 = AU["representation"]["per_feature_r2_on_23_baseline_diffs"]
    w(table([[k, DESC[k], f(v, 3), "largely already represented" if v >= 0.9 else ""] for k, v in r2.items()],
            ["feature", "meaning (A minus B)", "R² on baseline", "note"]))
    w("\n**Checks.** Truncation test: deleting every fight on or after "
      f"{AU['truncation_test']['cutoff']}, including opponents' later careers, changed no earlier feature (max difference "
      f"{AU['truncation_test']['max_abs_difference']} over {AU['truncation_test']['fights_compared']} fights). Fighter swap: "
      f"max |P(A,B) + P(B,A) − 1| = {R['swap_max_error']:.1e} over every test row of every model. The baseline reproduces "
      "SYM-002's regularised LR exactly.\n")

    w("## 3. Feature definitions (frozen before fitting)\n")
    w("All per-fighter rates use bouts strictly before the fight date, shrunk toward the league value to date (25 "
      "pseudo-minutes). `L_*` is that league value; it is the same for both corners, so it only sets units.\n")
    w("```\nW1 = (td15_A·tdag15_B − td15_B·tdag15_A) / L_td15\nW2 = (ctrl_A·ctrlag_B − ctrl_B·ctrlag_A) / L_ctrl\n"
      "W3 = tdacc_A·(1 − tddef_B) − tdacc_B·(1 − tddef_A)\nS1 = (slpm_A·sapm_B − slpm_B·sapm_A) / L_slpm\n"
      "S2 = (acc_A·(1 − def_B) − acc_B·(1 − def_A)) / L_acc\nS3 = (kd15_A·kdag15_B − kd15_B·kdag15_A) / L_kd15\n\n"
      "For each earlier bout b of fighter i against opponent k (k's rates taken going INTO bout b):\n"
      "  r_str_off  = landed/min(b)      − sapm_k,pre(b)\n  r_str_def  = slpm_k,pre(b)      − absorbed/min(b)\n"
      "  r_td_off   = td15(b)            − tdag15_k,pre(b)\n  r_td_def   = td15_k,pre(b)      − td-against15(b)\n"
      "  r_ctrl_off = ctrl share(b)      − ctrl-against_k,pre(b)\n  r_ctrl_def = ctrl share_k,pre(b) − ctrl-against(b)\n"
      "O_x(i) = Σ_b w_b·r_b / (Σ_b w_b + 15),   w_b = minutes_b · 0.5^(days_before_fight / 730)\n"
      "O1..O6 = O_x(A) − O_x(B)\n```\n")
    w("Model columns: the 23 baseline gaps `(zA − zB)/sd`, plus each new feature divided by its training standard deviation "
      "and clipped to ±5. L2 logistic regression, no intercept, λ chosen on inner validation per model per fold. Missing "
      "values → 0; none occurred on eligible rows. W and S use no extra time weighting, which isolates the value of the "
      "combination. O uses a two-year half-life.\n")

    w("## 4. Results, 2021–2025 (exploratory)\n")
    w(table([[LAB[m], P[m]["n"], f(P[m]["logloss"]), f(P[m]["brier"]), f"{P[m]['accuracy']*100:.1f}%",
              f"{P[m]['cal_intercept']:+.3f}", f(P[m]["cal_slope"], 3), f(P[m]["ece"], 3)] for m in MODELS],
            ["model", "fights", "log loss ↓", "Brier ↓", "accuracy", "cal. intercept", "cal. slope", "ECE"]))
    w("\n### Versus baseline (event-level bootstrap, 2,000 resamples)\n")
    w(table([[LAB[m], f"{v['diff']:+.4f}", f"{v['ci95'][0]:+.4f} to {v['ci95'][1]:+.4f}", f"{v['folds_better_of_5']}/5",
              ("**yes**" if v["meets_preregistered_rule"] else "no") if v["meets_preregistered_rule"] is not None else "n/a",
              f"{EX[m]['bonferroni_4_tests_98.75pct_ci'][0]:+.4f} to {EX[m]['bonferroni_4_tests_98.75pct_ci'][1]:+.4f}" if m in EX else "—"]
             for m, v in V.items()],
            ["model minus baseline", "log-loss diff", "95% CI", "years better", "meets rule?", "Bonferroni ×4 CI (descriptive)"]))
    w("\nNegative = better than baseline.\n")
    w("### Which years improved or worsened (log-loss difference vs baseline)\n")
    fd = R["fold_diffs_vs_baseline"]; ys = list(next(iter(fd.values())).keys())
    rows = [[LAB[m]] + [f"{fd[m][y]:+.4f}" for y in ys] for m in fd]
    rows.append(["fights / events"] + [f"{R['per_fold'][y]['baseline']['n']} / {R['per_fold'][y]['_n_events']}" for y in ys])
    w(table(rows, ["model"] + [y + (" (studied)" if y == "2026" else "") for y in ys]))
    worse = [y for y in ys if fd["baseline+O"][y] > 0]
    w(f"\nO is worse than baseline in: {', '.join(worse) if worse else 'no year'}; better in every other year.\n")
    w("### 2026 (already studied: historical research, not confirmation)\n")
    w(table([[LAB[m], H[m]["n"], f(H[m]["logloss"]), f"{H[m]['accuracy']*100:.1f}%",
              f"{V26[m]['diff']:+.4f} ({V26[m]['ci95'][0]:+.4f} to {V26[m]['ci95'][1]:+.4f})" if m in V26 else "—"] for m in MODELS],
            ["model", "fights", "log loss", "accuracy", "vs baseline (95% CI)"]))

    w("\n## 5. The frozen challenger: baseline + O\n")
    w(f"λ = {FO['lambda']:g}. Weights apply to standardised columns (`column = gap / training sd`). Here are the six new "
      "weights and the eight largest baseline weights:\n")
    wt = FO["weights"]
    r2 = AU["representation"]["per_feature_r2_on_23_baseline_diffs"]
    w(table([[k, DESC[k], f"{wt[k]:+.6f}", f"{FO['new_feature_train_std'][i]:.6f}"] for i, k in enumerate(FO["new_features"])],
            ["column", "meaning", "weight", "training sd"]))
    w("")
    w(table([[k, f"{v:+.6f}"] for k, v in EX["final_baseline+O_largest_base_weights"].items()], ["baseline gap", "weight"]))
    w("\nRead together: the opponent-adjusted striking columns (O1, O2) take the large positive weights, and the raw "
      "strikes-landed gap flips negative. The model swaps raw striking volume for *striking relative to the "
      "opposition*. These columns are correlated with the baseline (O1/O2 R² " + f"{r2['O1']:.2f}/{r2['O2']:.2f}" + "), so individual weights should "
      "not be read as separate effects. Full weights and preprocessing are in `private/models/sym003_final_baseline_plus_O.json`.\n")

    w("## 6. Frozen for unseen fights\n")
    w(table([[k, f"`{v}`"] for k, v in FZ["sha256"].items()], ["model", "SHA-256"]))
    w(f"\nTrained through {FZ['trained_through']}, frozen {FZ['frozen_at']}, valid for {FZ['prospective_from']}. "
      "Primary prospective comparison (pre-designated): **baseline+O vs baseline**. At the eligible-fight rate seen in "
      "recent years and an effect of this size, expect to need two or more years of cards before the comparison is decisive. "
      "Market comparisons should wait for CFL's own timestamped captures.\n")
    open(os.path.join(PRIV, "REPORT_SYM003.md"), "w").write("\n".join(md))
    print("wrote REPORT_SYM003.md")


if __name__ == "__main__":
    main()
